#!/usr/bin/env bash
# Script that configures a load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\

frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 4543-web-01 3.88.198.237 check
	server 4543-web-02 54.83.236.78 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
