#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.change
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.change
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.change
cp -f ~/hosts.change /etc/hosts
